apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.spiderdoctor.spidernet.io
spec:
  insecureSkipTLSVerify: true
  group: spiderdoctor.spidernet.io
  groupPriorityMinimum: 1000
  versionPriority: 100
  service:
    name: spiderdoctor-apiserver
    namespace: kube-system
  version: v1beta1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spiderdoctor-apiserver
  namespace: kube-system
  labels:
    apiserver: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      apiserver: "true"
  template:
    metadata:
      labels:
        apiserver: "true"
    spec:
      serviceAccountName: {{ .Values.spiderdoctorController.name | trunc 63 | trimSuffix "-" }}
      containers:
        - name: spiderdoctor-apiserver
          image: spiderdoctor-apiserver:latest
          imagePullPolicy: Never
          command:
            - /usr/bin/apiserver
---
apiVersion: v1
kind: Service
metadata:
  name: spiderdoctor-apiserver
  namespace: kube-system
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
  selector:
    apiserver: "true"

