---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.system.spiderdoctor.spidernet.io
  labels:
    {{- include "project.spiderdoctorController.labels" . | nindent 4 }}
      {{- if .Values.global.commonLabels }}
      {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
      {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations:
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  insecureSkipTLSVerify: true
  group: system.spiderdoctor.spidernet.io
  groupPriorityMinimum: 1000
  versionPriority: 100
  service:
    name: {{ .Values.spiderdoctorController.name | trunc 63 | trimSuffix "-" }}
    namespace: {{ .Release.Namespace | quote }}
  version: v1beta1
