apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.configName }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.global.commonLabels }}
  labels:
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
  {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations:
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  conf.yml: |
    enableIPv4: {{ .Values.feature.enableIPv4 }}
    enableIPv6: {{ .Values.feature.enableIPv6 }}
    taskPollIntervalInSecond: {{ .Values.feature.taskPollIntervalInSecond }}
    nethttp_defaultRequest_Qps: {{ .Values.feature.nethttp_defaultRequest_Qps }}
    nethttp_defaultRequest_MaxQps: {{ .Values.feature.nethttp_defaultRequest_MaxQps }}
    nethttp_defaultRequest_DurationInSecond: {{ .Values.feature.nethttp_defaultRequest_DurationInSecond }}
    nethttp_defaultRequest_PerRequestTimeoutInSecond: {{ .Values.feature.nethttp_defaultRequest_PerRequestTimeoutInSecond }}
    multusPodAnnotationKey: {{ .Values.feature.multusPodAnnotationKey }}
    crdMaxHistory: {{ .Values.feature.crdMaxHistory }}
